//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // dodato da bi se koristila anotacija
    using System.ComponentModel.DataAnnotations.Schema; // dodato da bi se koristilo NotMapped

    public partial class Artikal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikal()
        {
            this.StavkaNarudzbenicas = new HashSet<StavkaNarudzbenica>();
            this.StavkaRacuns = new HashSet<StavkaRacun>();
        }

        [Required(ErrorMessage = "Sifra artikla je obavezna")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        public int ArtikalID { get; set; }

        [Required(ErrorMessage = "Naziv artikla je obavezan")]
        public string NazivArtikla { get; set; }

        [Required(ErrorMessage = "Cena artikla je obavezna")]
        [ValidacijaCena(ErrorMessage = "Format cene artikla")]
        public float Cena { get; set; }

        [Required(ErrorMessage = "Kolicina artikla je obavezna")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        [ValidacijaKolicina(ErrorMessage = "Format kolicine artikla")]
        public int Kolicina { get; set; }

        public int Dobavljac { get; set; }

        public Nullable<int> Aktivan { get; set; }

        [NotMapped]
        public List<Dobavljaci> ListaDobavljaci { get; set; }
        public virtual Dobavljaci Dobavljaci { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaNarudzbenica> StavkaNarudzbenicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacun> StavkaRacuns { get; set; }
    }
}