//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // dodato da bi se koristila anotacija

    public partial class Dobavljaci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dobavljaci()
        {
            this.Artikals = new HashSet<Artikal>();
        }

        [Required(ErrorMessage = "Sifra dobavljaca je obavezna")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        public int DobavljacID { get; set; }

        [Required(ErrorMessage = "Naziv dobavljaca je obavezan")]
        public string NazivDobavljaca { get; set; }

        [Required(ErrorMessage = "Adresa dobavljaca je obavezna")]
        public string Adresa { get; set; }

        [Required(ErrorMessage = "Telefon dobavljaca je obavezan")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        [StringLength(7, MinimumLength = 7, ErrorMessage = "Telefon ima 7 cifara")]
        public string Telefon { get; set; }

        public Nullable<int> Aktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artikal> Artikals { get; set; }
    }
}