//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // dodato da bi se koristila anotacija
    using System.ComponentModel.DataAnnotations.Schema; // dodato da bi se koristilo NotMapped

    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Narudzbenicas = new HashSet<Narudzbenica>();
            this.Racuns = new HashSet<Racun>();
        }

        [Required(ErrorMessage = "Korisnicko ime korisnika je obavezno")]
        public string KorisnickoIme { get; set; }

        [Required(ErrorMessage = "Ime korisnika je obavezno")]
        [RegularExpression("[a-zA-Z]+", ErrorMessage = "Moze se uneti malo ili veliko slovo")]
        public string Ime { get; set; }

        [Required(ErrorMessage = "Prezime korisnika je obavezno")]
        [RegularExpression("[a-zA-Z]+", ErrorMessage = "Moze se uneti malo ili veliko slovo")]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "JMBG korisnika je obavezan")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        [StringLength(13, MinimumLength = 13, ErrorMessage = "JMBG ima 13 cifara")]
        public string JMBG { get; set; }

        [Required(ErrorMessage = "Lozinka korisnika je obavezna")]
        public string Lozinka { get; set; }

        public int Uloga { get; set; }

        [NotMapped]
        public List<Uloge> ListaUloge { get; set; }
        public virtual Uloge Uloge { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzbenica> Narudzbenicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
    }
}