//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjizara.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // dodato da bi se koristila anotacija
    using System.ComponentModel.DataAnnotations.Schema; // dodato da bi se koristilo NotMapped

    public partial class StavkaNarudzbenica
    {
        public int Narudzbenica { get; set; }

        [Required(ErrorMessage = "Redni broj stavke narudzbenice je obavezan")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        public int RedniBroj { get; set; }

        public int Artikal { get; set; }

        [Required(ErrorMessage = "Kolicina stavke narudzbenice je obavezna")]
        [RegularExpression("[0-9]+", ErrorMessage = "Moze se uneti cifra")]
        [ValidacijaKolicina(ErrorMessage = "Format kolicine stavke narudzbenice")]
        public int Kolicina { get; set; }

        public float Cena { get; set; }

        [NotMapped]
        public List<Artikal> ListaArtikal { get; set; }
        public virtual Artikal Artikal1 { get; set; }

        [NotMapped]
        public List<Racun> ListaRacun { get; set; }
        public virtual Narudzbenica Narudzbenica1 { get; set; }
    }
}